clone:
  path: github.com/cipemotion/commonmark

build:
  test-php70:
    image: tetraweb/php:7.0
    commands:
      - docker-php-ext-enable xdebug zip mcrypt mbstring
      - php -v
      - composer self-update
      - composer install --no-progress --no-scripts
      - php vendor/bin/phpunit --coverage-text --colors=never
