kind: pipeline
name: test

clone:
  depth: 1

steps:
  - name: composer
    pull: always
    image: stayallive/composer-install

  - name: php71
    pull: always
    image: stayallive/php:7.1
    depends_on: [composer]
    commands:
      - docker-php-ext-enable zip mcrypt bcmath pcntl
      - php vendor/bin/phpunit --colors=never

  - name: php72
    pull: always
    image: stayallive/php:7.2
    depends_on: [composer]
    commands:
      - docker-php-ext-enable zip bcmath pcntl
      - php vendor/bin/phpunit --colors=never

  - name: php73
    pull: always
    image: stayallive/php:7.3
    depends_on: [composer]
    commands:
      - docker-php-ext-enable zip bcmath pcntl
      - php vendor/bin/phpunit --colors=never
