clone:
  git:
    image: plugins/git
    depth: 1

build:
  test-php71:
    image: stayallive/php:7.1
    commands:
      - docker-php-ext-enable zip mcrypt bcmath pcntl
      - php -v
      - composer self-update
      - composer install --no-progress --no-scripts
      - php vendor/bin/phpunit --coverage-text --colors=never
  test-php72:
    image: stayallive/php:7.2
    commands:
      - docker-php-ext-enable zip mcrypt bcmath pcntl
      - php -v
      - composer self-update
      - composer install --no-progress --no-scripts
      - php vendor/bin/phpunit --coverage-text --colors=never
