image: tetraweb/php:5.6

before_script:
  - docker-php-ext-enable xdebug zip mcrypt mbstring

stages:
  - cs
  - test

php-5.6:
  type: test
  image: tetraweb/php:5.6
  script:
    - php -v
    - composer self-update
    - composer install --no-progress --no-scripts
    - php vendor/bin/phpunit --coverage-text --colors=never
  except:
    - tags

php-7.0:
  type: test
  image: tetraweb/php:7.0
  script:
    - php -v
    - composer self-update
    - composer install --no-progress --no-scripts
    - php vendor/bin/phpunit --coverage-text --colors=never
  except:
    - tags

phpcs:
  type: cs
  script:
    - php -v
    - phpcs --version
    - phpcs -p --standard=PSR2 src/
  only:
    - develop
