image: tetraweb/php:5.6-cli

before_script:
  - docker-php-ext-enable zip
  - docker-php-ext-enable mbstring

variables:
  WITH_XDEBUG: "1"

stages:
  - cs

phpcs:
  type: cs
  script:
    - php -v
    - phpcs --version
    - phpcs -p --standard=PSR2 src/
  only:
    - develop
